spring.application.name=LAB05
spring.datasource.url=jdbc:mysql://localhost:3306/bai5_qlsp
spring.datasource.username=root
spring.datasource.password=slam7424

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081